import Head from "next/head";
import { Dai_Banna_SIL, Inter } from "next/font/google";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

/*const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});*/

export default function Home() {
  return (
    <>
    <title> 
      <Head>
        <div>
          <p1>Welcome to my Blog!</p1>
          <p> Check out my <Link href="/posts/first-post">first post</Link></p>
        </div>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      </title>
    </>
  );
}
